// vue/src/components/tickets/CreateTicket.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import TicketModal from "./TicketModal.vue";
import { createTicket } from "@ticketapp/shared";

defineProps<{
  onClose: () => void;
}>();

const router = useRouter();
const onSubmit = async (e: SubmitEvent) => {
  await createTicket(e);
  router.go(0);
};
</script>

<template>
  <TicketModal :onSubmit="onSubmit" :onClose="onClose" />
</template>

// react/src/components/tickets/CreateTicket.tsx
import { createTicket } from "@ticketapp/shared";
import TicketModal from "./Modal";

export default function CreateTicket({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  if (!open) return null;

  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    await createTicket(e);
    window.location.reload();
  };

  return <TicketModal onSubmit={onSubmit} onClose={onClose} />;
}
