// react/src/components/tickets/EditTicket.tsx
import { updateTicket, type Ticket } from "@ticketapp/shared";
import TicketModal from "./Modal";

export default function EditTicket({
  open,
  onClose,
  ticket,
}: {
  open: boolean;
  onClose: () => void;
  ticket: Ticket;
}) {
  if (!open) return null;

  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    await updateTicket(e, ticket.id);
    window.location.reload();
  };

  return <TicketModal onSubmit={onSubmit} onClose={onClose} ticket={ticket} />;
}

// vue/src/components/tickets/EditTicket.vue
<script setup lang="ts">
import { updateTicket, type Ticket } from "@ticketapp/shared";
import TicketModal from "./TicketModal.vue";
import { useRouter } from "vue-router";

const { ticket } = defineProps<{
  onClose: () => void;
  ticket: Ticket;
}>();

const router = useRouter();
const onSubmit = async (e: SubmitEvent) => {
  await updateTicket(e, ticket.id);
  router.go(0);
};
</script>

<template>
  <TicketModal :onSubmit="onSubmit" :onClose="onClose" :ticket="ticket" />
</template>
